version: '2'
services:
  litecoind:
    restart: always
    build:
      context: .
      args:
        LITECOIN_VER: "0.15.1"
    ports:
      - "8332:9332"                            # rpc server port
      - "8333:9333"
      - "19332:19332"                          # testnet
      - "19333:19333"
    environment:
      RPCUSER: "user"
      RPCPASS: "pass"
      RPCALLOWIP: "0.0.0.0/0"
    #command: -onlynet=ipv4 -testnet
    volumes:
      - "~/.litecoin:/data"                     # bitcoin node data directory

